### ISSUE TITLE
Support for `-Z asm-comments`

### ISSUE THREAD

**Issue by str4d** [pacak/cargo-show-asm#118]
This is a nightly-only `rustc` config option that causes LLVM to preserve assembly comments. It can be useful for debugging in combination with `core::arch::asm!("nop # Some Comment");`.

Currently if I attempt to apply this manually, it breaks:
```
$ RUSTFLAGS="-Z asm-comments" cargo +nightly asm ...
...
  Finished release [optimized] target(s) in 0.01s
Error: Couldn't find any items to display
```

**Comment by pacak** [comment]
Released 0.2.10, should be working now.
