### ISSUE TITLE
Error: Compilation produced multiple matching files: ..,  this is a bug

### ISSUE THREAD

**Issue by luctius** [pacak/cargo-show-asm#12]
When using the project below, I get `Error: Compilation produced multiple matching files: [Ok("/home/<user>/tmp/hello/target/thumbv7em-none-eabihf/release/deps/hello-4b3303ff09815de6.s"), Ok("/home/<user>/tmp/hello/target/thumbv7em-none-eabihf/release/deps/hello-e1fd39ec783ba3fe.s")], this is a bug`

In the sample project --bin works while --lib fails, though in my bigger project both fail. I am unsure what the difference is and will look at it later.

Requires the `cross` branch.

Create project and enter
```
cargo new hello
cd hello
```
Modify main.rs
```
echo '#![no_main]
#![no_std]

use defmt_rtt as _;
use panic_halt as _;

#[inline(never)]
pub fn print() {
    defmt::error!("idle loop");
}' > src/lib.rs
```
Add binary
```
mkdir -p src/bin &&
echo '#![no_main]
#![no_std]

use cortex_m_rt::entry;

use hello::print;

#[entry]
fn main() -> ! {
    loop {
        print();
    }
}' > src/bin/hello.rs
```

Set-up Cargo.toml
```
echo 'cortex-m = "0.6.2"                                                                        
cortex-m-rt = "0.6.11"
panic-halt = "0.2.0"
defmt = "0.3.0"
defmt-rtt = "0.3.0"' >> Cargo.toml
```

get necessary memory.x and set-up .cargo/config
```
wget https://raw.githubusercontent.com/stm32-rs/stm32g4xx-hal/master/memory.x
mkdir .cargo
echo '[target.thumbv7em-none-eabihf]
runner = "arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Map=.linker.map",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"' > .cargo/config
```

`cargo asm --lib hello::print`  <-- Fails
`cargo asm --bin hello hello::__cortex_m_rt_main` <-- Works

**Comment by pacak** [comment]
Hmmm... Yea, that's my fault, I forgot about this check... Will fix.

**Comment by pacak** [comment]
So problem was with "cargo clean" only cleaning the host target by default. I changed the implementation a bit and now both examples are working. Can you check if updated cross branch is working with your project?

**Comment by pacak** [comment]
`cargo asm --lib hello::print` <-- Fails
`cargo asm --bin hello hello::__cortex_m_rt_main` <-- Works

FWIW problem here is caused by two separate targets producing the same asm file: `hello.s`. cleaning helps with this specific example since it can only produce one of those files during a run, but if your project produces both - it still won't work. cargo-show-asm can't check several files since they can also be stale copies left behind from older compilations.

**Comment by pacak** [comment]
Should be working now, feel free to reopen if you have a different reproduer.
