### ISSUE TITLE
`Error: Compilation produced no files satisfying .\target\release\deps\[crate name]-*.s, this is a bug`

### ISSUE THREAD

**Issue by griffi-gh** [pacak/cargo-show-asm#132]
```
    Finished release [optimized] target(s) in 0.35s
Error: Compilation produced no files satisfying .\target\release\deps\kubi-*.s, this is a bug
```

**Comment by griffi-gh** [comment]
Sorry, this was an issue on my end

**Comment by pacak** [comment]
Well, that was fast. What was the problem?

**Comment by griffi-gh** [comment]
> Well, that was fast. What was the problem?

installed an old version of the crate somehow

**Comment by griffi-gh** [comment]
> Well, that was fast. What was the problem?

installed an old version of the crate somehow
