### ISSUE TITLE
Error: Unknow target kind: ["cdylib"]

### ISSUE THREAD

**Issue by pacak** [pacak/cargo-show-asm#135]
https://github.com/david-wallace-croft/com-croftsoft-app-life

**Comment by pacak** [comment]
https://doc.rust-lang.org/reference/linkage.html

**Comment by phi-gamma** [comment]
FWIW I had to remove the ``cdylib`` from the ``crate_type`` to get ``cargo asm`` to work. Otherwise I get ``Error: Cannot locate the path to the asm file``. Not sure if that’s the right issue for this, looked pertinent enough. ;)

**Comment by pacak** [comment]
Totally the right issue. Need to figure out where it places the final results from info available in the artifact report. Any ideas?

**Comment by pacak** [comment]
https://github.com/pacak/cargo-show-asm/blob/master/src/main.rs#L258 basically this function

**Comment by pacak** [comment]
@phi-gamma What OS are you using? I got it working with Linux but not with Windows/MacOS...

**Comment by phi-gamma** [comment]
2023-02-03 (Friday), ***@***.*** (pacak):

> @phi-gamma What OS are you using? I got it working with Linux but not with Windows/MacOS...

Arch Linux, x86-64.

Thanks for working on this, I’ll try out 0.2.13 on Monday when
I’m back at my work machine.

**Comment by phi-gamma** [comment]
Good news, 0.2.13 works for me without removing `cdylib`!
