### ISSUE TITLE
Flag to emit LLVM IR before any LLVM passes

### ISSUE THREAD

**Issue by jonasmalacofilho** [pacak/cargo-show-asm#142]
Sometimes it seems to be useful to look at the LLVM IR generated by Rust with optimizations enabled, but before any LLVM passes. One example is to look for whether an argument to a function that will be inlined has `noalias`.

Implementation-wise, this can be done by passing [`-C no-prepopulate-passes`][`no-prepopulate-passes`] to rustc.

I think it would be convenient if cargo-show-asm could do this (and I can send a PR), but I'm not sure what would be the best way to expose the feature in the CLI:

- a separate flag, something like `--rust-llvm` or `--llvm-input`?
- an optional parameter to the existing `--llvm` flag, something like `--llvm=rust` or `--llvm=input`?
- mimicking rustc and adding flags for both [`no-prepopulate-passes`] and [`passes`]?
- something else?

[`no-prepopulate-passes`]: https://doc.rust-lang.org/stable/rustc/codegen-options/index.html#no-prepopulate-passes
[`passes`]: https://doc.rust-lang.org/stable/rustc/codegen-options/index.html#passes

---

EDIT: of course, this can already be done by passing `-C no-prepopulate-passes` through `RUSTFLAGS`. But that's quite unwieldy to type, and I'm guessing it's not that uncommon for those looking into LLVM IR to want to [also] see it before the LLVM passes.

**Comment by pacak** [comment]
> and I can send a PR

Sounds good, let me know if you have any questions. Alternatively I can give it a go myself but it might take a few days.
