### ISSUE TITLE
lto support is disabled 

### ISSUE THREAD

**Issue by pacak** [pacak/cargo-show-asm#148]
https://github.com/pacak/cargo-show-asm/issues/146

**Comment by zeroflaw** [comment]
I has to downgrade to cargo-show-asm v0.2.14, as LTO is working for me in this version. 
rustup 1.25.2 (17db695f1 2023-02-01)

**Comment by pacak** [comment]
What kind of lto are you using and what kind of a problem do you have with current version? Unless I'm mistaken current state is to compile the whole crate as a single codegen unit which should give result similar to lto, just not across multiple crates.

**Comment by pacak** [comment]
Hack was reverted in 0.2.20, looks like 1.67.1 had some sort of temporary regression.
