### ISSUE TITLE
index out of bounds on 0.2.16

### ISSUE THREAD

**Issue by dave-wathen** [pacak/cargo-show-asm#157]
This seems similar to https://github.com/pacak/cargo-show-asm/issues/65 but that was fixed in 0.1.24.

rust-src seems to be fine:
> $ rustup component add rust-src
> info: component 'rust-src' is up to date

I've attached the output from:

> $ cargo asm --intel --lib 5 --rust -vvvv

[cargo_asm_out.txt](https://github.com/pacak/cargo-show-asm/files/11186064/cargo_asm_out.txt)

**Comment by pacak** [comment]
Hashbrown again. :thinking: 

Well, it tries and fails to find it's sources. Do you have this file on your machine? Or is it located somewhere else?
```
Reading file #31 /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.3/src/map.rs
File not found /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.3/src/map.rs
```

This code had several problems, maybe I should change the behavior to print a warning instead of panicking...

**Comment by pacak** [comment]
I suspect the file is under `/Users/dave/` somewhere and `/Users/runner` comes from how rust is compiled with hashbrown being part of precompiled stdlib and this is part of the runner leaking...

Anyway. I pushed a version that tries to apply the same workaround as I did on linux to `hb-mac`. Can you see if it fixes the problem for you?

**Comment by pacak** [comment]
Last two comments seem related to this problem. https://bugzilla.mozilla.org/show_bug.cgi?id=1717973

**Comment by dave-wathen** [comment]
Sorry didn't see your responses until now.  It now works with 0.2.17.  Looks like all your comments are correct :).

Thanks for fixing so quickly!

**Comment by pacak** [comment]
> Sorry didn't see your responses until now.

No worries :)

> It now works with 0.2.17.

Good to hear, thanks for confirming.
