### ISSUE TITLE
Should `cargo-show-asm` assume "dev profile" by default, not release?

### ISSUE THREAD

**Issue by PoignardAzur** [pacak/cargo-show-asm#163]
## The issue

Right now, running

```sh
cargo asm foobar
```

is equivalent to

```sh
cargo asm --release foobar
```

and the dev profile requires

```sh
cargo asm --dev foobar
```

Eg, the release profile is the default. There are obvious benefits to this, since most of the time you want the assembly of your release binary, since it's the one you're likely trying to optimize. Having release be the default saves you from having to type `--release` every time, makes the commands shorter, etc.

I'd still argue it's the wrong default.

As far as I know, absolutely every other cargo command assumes `--dev` by default. Having a different for cargo-show-asm is unexpected; it's something you have to actively remind yourself of.

## Ok, but why should we care?

Well, cargo-show-asm is primarily a debugging / benchmarking tool, right?

Most of the time, you're going to be using it because your program doesn't exhibit the performance characteristics you expect, and you want to find out why.

But say you're an absolute idiot (like me).

You might then run your program with `cargo run -- some args`, and have unexpected performance characteristics. You might then use `cargo asm foobar` to check some function taking up most of your program's runtime, and see that the assembly is roughly what you expected, something that should run much faster than your program does.

What you might not realize for *a while* is that `cargo asm` is *not*, in fact, examining the binary executed by `cargo run`, because the latter will be in dev profile while the former will be in release profile.

And, okay, if I'm that idiot, part of that is on me for not realizing sooner that I was trying to benchmark an unoptimized version of my program.

But the process of realizing that requires me to use various tools to gain an understanding of my program and notice my obvious mistakes. When one of those tools, cargo-show-asm, behaves in a way that violates a basic expectation of mind that I didn't think to double-check (that `cargo asm` would display the code executed by `cargo run`), finding my root mistake takes much longer than it did if my tools kept to the principle of least expectation.

(I hope I'm not coming off as abrasive here. I'm belaboring the point a lot, not because I think it's obvious and the maintainers are stupid for not seeing it, but because I think it's subtle and I'm struggling to put it into words.)

Anyway, if genuinely think `--dev` would be a better default, even if it makes everybody's commands a little longer.

**Comment by pacak** [comment]
> But say you're an absolute idiot (like me).

If you can understand whatever `cargo-show-asm` outputs - you are not an idiot already :)

The way I see `cargo-show-asm` is a tool to understand what rustc/llvm are doing at every level. There's usually very little reason to try to understand what's going on in dev profile - there will be no optimizations, there will be extra runtime checks, etc and this is not the code that you will actually run in production.

That said I can add a way to override the default profile by specifying an env variable. Would it help in your case?

**Comment by PoignardAzur** [comment]
> The way I see cargo-show-asm is a tool to understand what rustc/llvm are doing at every level. There's usually very little reason to try to understand what's going on in dev profile - there will be no optimizations, there will be extra runtime checks, etc and this is not the code that you will actually run in production.

Right, I understand that there's usually little reason to want to introspect the dev profiles.

My point though is, the cargo ecosystem has an unstated rule that cargo commands with the same arguments will have the same target. So `cargo check` will check the same version of the program as `cargo build`, `cargo run` will run it, etc. `cargo-show-asm` subtly breaks that rule on the basis that "the dev version is probably not that you want".

And yeah, I get the rationale, unoptimized code is indeed probably not what you want to check.

At the same time, it creates an invisible footgun, because "what you're inspecting by default" is different from "what you're executing by default"; because the user might not be thinking about profiles at all. So the only way to be aware of that footgun is to shoot it.

In that sense, the solution you propose would help once you've shot your foot off, but it wouldn't help you see it coming, I guess.

(That said, if it's the only option available, yes, I'll gladly take it.)

**Comment by pacak** [comment]
> In that sense, the solution you propose would help once you've shot your foot off, but it wouldn't help you see it coming, I guess.

I can add it to the documentation too :)

> (That said, if it's the only option available, yes, I'll gladly take it.)

Well. I can give you the override without affecting anyone else, 10-15 minutes of work in total. Changing the default behavior is https://xkcd.com/1172/ which is a big breaking change, for that I need to look around how people are using it. Not totally out of the question but requires more consideration, plus having a way to override it would allow me to keep using `cargo asm ...`

**Comment by pacak** [comment]
> 10-15 minutes of work in total.

Hmmm. Blocked on me releasing `bpaf` 0.8.0 for a cleaner solution.

Anyway. I'll add the override for you, will update the docs mentioning it and default profile shenanigans and will keep the ticket open to collect more opinions. With more votes in favor of changing the default profile - will look into releasing cargo-show-asm 0.3.0 or something.

**Comment by PoignardAzur** [comment]
Awesome! I appreciate your thoughtfulness in considering different options.

**Comment by pacak** [comment]
Okay, I released 0.2.18, you can set the default profile using `CARGO_SHOW_ASM_PROFILE`. This ticket stays open for more feedback.

**Comment by PSeitz** [comment]
When I look at assembly, I want to understand the commands the CPU is receiving to analyze performance. That is never in dev.

I understand the rationale though that an absolute beginner doesn't know about `--release`. Some documentation should be enough imo and is the faster way than to look at the debug assembly, and realize it's debug assembly.

**Comment by pacak** [comment]
Okay, I think the consensus is that `--release` is a sane default.
