### ISSUE TITLE
asm output for benchmarks not showing up

### ISSUE THREAD

**Issue by hecatia-elegua** [pacak/cargo-show-asm#165]
example: `cargo asm -p project --bench teststuff main`
![image](https://user-images.githubusercontent.com/108802164/234540583-1113e22c-7ad2-4e90-8c9e-4777452cae1d.png)
some more info:
![image](https://user-images.githubusercontent.com/108802164/234546831-83d7c1e8-9faf-470c-9e45-1f36a448bf0a.png)

The example might be contrived or I'm doing something wrong, but I haven't gotten this to output the asm of benchmarks, let alone show me the actual functions when listing. I'm using criterion. It also doesn't work with a real, working criterion benchmark.

Please tell me what other info I should provide.

**Comment by pacak** [comment]
Last line on the first screenshot says it is calling `test_main_static`, do you see it if you call `cargo asm -p project --bench teststuff --everything`?

If not - what are the versions of `rustc`, `cargo-show-asm`? What platform are you on? Can you share the full code?

**Comment by hecatia-elegua** [comment]
if I pipe with `--everything` into a file, `test_main_static` doesn't show up anywhere, `inner` shows up like this:
![image](https://user-images.githubusercontent.com/108802164/234563998-82bfbf4c-cd82-4ae1-a30c-9dc9ca254861.png)

rustc 1.67.0-nightly (edf018221 2022-11-02)
cargo-show-asm 0.2.17
win10

**Comment by hecatia-elegua** [comment]
Here's the real code: https://github.com/hecatia-elegua/bilge/blob/main/benches/compared

Ok strange, if I add `#[inline(never)]` to these function, which I'm calling in `compared/main.rs`, they do show up now:
![image](https://user-images.githubusercontent.com/108802164/234566491-a75c81e9-9249-4003-8ece-6d8927ddbafc.png)
I thought I did that already...

Well that solved it, produces what I expected.

**Comment by pacak** [comment]
Magic.

**Comment by hecatia-elegua** [comment]
funny enough, `inner` in this dumb example doesn't show up anyways, even if it's inline-never...
though I don't need that solved, so

thanks for this nice tool :)

**Comment by pacak** [comment]
Can you publish this dumb example somewhere?

**Comment by hecatia-elegua** [comment]
https://github.com/hecatia-elegua/asmrepro

**Comment by pacak** [comment]
> https://github.com/hecatia-elegua/asmrepro

This version does not use criterion and it seems like default bench harness from `cargo`/`rustc` replaces `main` function with something that would run actual benches. If you replace body of your `main` with `panic!("this never runs")` and try to run the benchmarks - it successfully runs showing 0 total tests.
