### ISSUE TITLE
unreadable colours

### ISSUE THREAD

**Issue by hfiguiere** [pacak/cargo-show-asm#170]
When running `cargo asm`  the output in the terminal uses colours that are unreadable.

![image](https://github.com/pacak/cargo-show-asm/assets/114441/4441d8bb-66c8-4870-996a-76c24b5909a8)

And even selected:

![image](https://github.com/pacak/cargo-show-asm/assets/114441/de4a724c-127a-42ae-b258-5c9f4ea8cf49)

**Comment by pacak** [comment]
This is unfortunate. Are you running some custom color scheme? What
terminal/OS do you use?

**Comment by hfiguiere** [comment]
GNOME Terminal, and this one is set to use "Solarized Dark" colour scheme. Note that with the Dark system theme is barely readable anyway.

![image](https://github.com/pacak/cargo-show-asm/assets/114441/bd243303-74d2-4237-8dc0-2928d9d517b4)

**Comment by pacak** [comment]
Interesting, it looks different on my machine. I'll do some research about picking colors, etc and will see what can I do about this. Meanwhile you can use `--no-color` or piping output of `cargo-show-asm` to `less`

**Comment by epontan** [comment]
I think it is the use of `OwoColorize::bright_black` that makes it look bad on dark color schemes. Changing the instances where `bright_black` is used with something else makes it look great.

I can create a PR with a suggestion of changes if you agree?

**Comment by pacak** [comment]
> I can create a PR with a suggestion of changes if you agree?

Sure. What color do you have in mind?

**Comment by epontan** [comment]
> Sure. What color do you have in mind?

Great! I created PR #236 as a proposal of colors. I tried to separate them a little bit depending on semantics, but maybe you already have some defined color semantics in place (that I might have missed) which you want instead.
