### ISSUE TITLE
Fails with -Z asm-comments

### ISSUE THREAD

**Issue by farnoy** [pacak/cargo-show-asm#193]
I don't have a small repro, will try to create one.

When I do `$ RUSTFLAGS="-Zasm-comments" cargo asm  --intel` I get `Error: stream did not contain valid UTF-8`, it doesn't list the functions, nor can I use it to dump asm of a specific function.

The error seems invalid, doing `$ file target/release/deps/*.s` outputs `assembler source, ASCII text, with very long lines (331)`

This is on `0.2.20`, `rustc 1.73.0-nightly (474709a9a 2023-08-03)`

**Comment by pacak** [comment]
I'm on `0.2.21` and the same compiler, this line works for me in my example. You can try passing a bunch of `-vvv` or making a small repro.

**Comment by farnoy** [comment]
It just says:

```
Artifact files: ["<binary path, valid>"]
Asm file: <path, also valid>
goal: Unspecified

Error: stream did not contain valid UTF-8
```

**Comment by pacak** [comment]
After printing the goal it tries to read the asm file so there's something wrong with it. You can try reading it yourself. Depending on what part is not a valid utf8 - it might be a bug in rustc/llvm.

```rust
    if fmt.verbosity > 2 {                                       
        safeprintln!("goal: {goal:?}");              
    }                                                       
                                                                                    
    let contents = std::fs::read_to_string(path)?; => String
```

**Comment by farnoy** [comment]
I tried [this method ](https://stackoverflow.com/questions/29465612/how-to-detect-invalid-utf8-unicode-binary-in-a-text-file) to identify those bytes And these are `.byte 230 # <weird char here>` annotations. I think that means that LLVM is emitting a printable character for some of the debug annotations. Here's an example:

```
.Ldebug_loc1737:
	.quad	-1
	.quad	.Lfunc_begin33                  #   base address
	.quad	.Ltmp3178-.Lfunc_begin33
	.quad	.Ltmp3191-.Lfunc_begin33
	.short	6                               # Loc expr size
	.byte	158                             # DW_OP_implicit_value
	.byte	4                               # 4
	.byte	149                             #
	.byte	191                             #
	.byte	214                             # �
                                                   	.byte	51 # 3
	.quad	.Ltmp3192-.Lfunc_begin33
	.quad	.Ltmp3226-.Lfunc_begin33
	.short	6                               # Loc expr size
	.byte	158                             # DW_OP_implicit_value
	.byte	4                               # 4
	.byte	149                             #
	.byte	191                             #
	.byte	214                             # �
```

It's those `.byte 214`  have that non-UTF-8 character.

I then tried [this](https://stackoverflow.com/a/17048486):

```sh
$ iconv -f utf-8 -t utf-8 -c $goal > tmp
$ mv tmp $goal
$ cargo asm  ...
```

And it worked, outputting both LLVMs comments as well as those emitted by me with `asm!("# LLVM-MCA-BEGIN")`

**Comment by pacak** [comment]
I see. I can't replicate it :) I would say this is a bug in llvm/rustc after all and would appreciate you trying to make a minimal example and making a bug around here: https://github.com/rust-lang/rust/issues

Meanwhile I'll look into making a workaround.

**Comment by pacak** [comment]
What platform are you on?

**Comment by pacak** [comment]
I pushed a branch called `hack`. Can you see if `cargo install --git https://github.com/pacak/cargo-show-asm/ --branch hack` fixes your problem?

**Comment by farnoy** [comment]
This was on linux with `--target x86_64-unknown-linux-gnu -C link-arg=-fuse-ld=lld -Z asm-comments`. It works on Windows with `--target x86_64-pc-windows-msvc -C linker=lld -Z asm-comments`, but I don't have a need for it there since I don't have the llvm-mca binary distributed with LLVM on Windows.

**Comment by farnoy** [comment]
That fixes the normal assembly view, but there are other uses of `fs::read_to_string` and commands like `--mca-intel` still fail with the same error as before.

**Comment by pacak** [comment]
Sort of fixed
