### ISSUE TITLE
How to dump disassembly of PGO optimized builds?

### ISSUE THREAD

**Issue by playXE** [pacak/cargo-show-asm#196]
The question is in issue name. I am using cargo-pgo for doing PGO builds, is there any way to use cargo asm on it?

**Comment by pacak** [comment]
Not at the moment. I might add it at some point.

**Comment by playXE** [comment]
What are the required steps to add it? I might make a PR as it is important feature for me. 
@pacak

**Comment by pacak** [comment]
Currently cargo-show-asm works by asking rustc to produce an `.s` file (and more importantly explain where this file was produced). If `cargo-pgo` can do that adding should be relatively easy. If it can't - maybe make a feature request with them.

Second approach would be running `objdump` on the generated binary and doing the same stuff it does already for `.s` files. I wanted to implement this at some point, even made a ticket #174 :) I think current asm parser might be extended just enough to support this.
