### ISSUE TITLE
Missing license files

### ISSUE THREAD

**Issue by orhun** [pacak/cargo-show-asm#213]
The project is dual licensed under MIT + Apache licenses but the repository contains no related files.

e.g. this is needed for distro packagers to include the license file in the `cargo-show-asm` package.

Please consider adding license files - you can check out [this repo](https://github.com/orhun/daktilo/blob/main/LICENSE-MIT) for an example.

**Comment by pacak** [comment]
Added. Maybe `clippy` or `cargo` should complain about that at some of the more pedantic settings. Or something around "how to publish a crate documentation" should mention it.

**Comment by orhun** [comment]
Yeah I agree. I think `cargo clippy` warns about missing `license` field if you deny `clippy::cargo` but not for the actual license files.

Can we get a new release along with this change? 🐻

**Comment by pacak** [comment]
> Can we get a new release along with this change? 🐻

Yea, I'll try to make one soon-ish.

**Comment by pacak** [comment]
I released 0.2.22 (#218)
