### ISSUE TITLE
color output can be very difficult to read on dark backgrounds

### ISSUE THREAD

**Issue by elagergren-spideroak** [pacak/cargo-show-asm#264]
Cargo: `cargo 1.77.0 (3fe68eabf 2024-02-29)`
cargo-asm: `Version: 0.2.30`

<img width="321" alt="Screenshot 2024-04-10 at 10 57 19" src="https://github.com/pacak/cargo-show-asm/assets/36516532/32c4d0cd-6167-4b1e-9bdb-f0decae0e34a">

**Comment by pacak** [comment]
I think should drop whatever magic I'm doing for `#`...
