### ISSUE TITLE
`--simplify` removes inline assembly

### ISSUE THREAD

**Issue by elagergren-spideroak** [pacak/cargo-show-asm#265]
Cargo: `cargo 1.77.0 (3fe68eabf 2024-02-29)`
cargo-asm: `Version: 0.2.30`

<details>
<summary>Without --simplify</summary>
<pre>
.section __TEXT,__text,regular,pure_instructions
	.build_version macos, 11, 0
	.globl	dit::with_dit
	.p2align	2
dit::with_dit:
Lfunc_begin0:
	.cfi_startproc
	stp x29, x30, [sp, #-16]!
	.cfi_def_cfa_offset 16
	mov x29, sp
	.cfi_def_cfa w29, 16
	.cfi_offset w30, -8
	.cfi_offset w29, -16
	mov x9, #68719411200
	movk x9, #49168
	ldr x8, [x9]
	tbz x8, #57, LBB0_4
	; InlineAsm Start
	.long	3577430696
	; InlineAsm End
	tbnz w8, #24, LBB0_4
	; InlineAsm Start
	.long	3573760351
	; InlineAsm End
	ldr x8, [x9]
	tbz x8, #57, LBB0_5
	; InlineAsm Start
	.long	3573760095
	; InlineAsm End
	b LBB0_5
	ldr xzr, [x9]
LBB0_5:
	mov w0, #42
	.cfi_def_cfa wsp, 16
	ldp x29, x30, [sp], #16
	.cfi_def_cfa_offset 0
	.cfi_restore w30
	.cfi_restore w29
	ret
</pre>
</details>

<details>
<summary>With --simplify</summary>
<pre>
dit::with_dit:
Lfunc_begin0:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	mov x9, #68719411200
	movk x9, #49168
	ldr x8, [x9]
	tbz x8, #57, LBB0_4
	tbnz w8, #24, LBB0_4
	ldr x8, [x9]
	tbz x8, #57, LBB0_5
	b LBB0_5
	ldr xzr, [x9]
LBB0_5:
	mov w0, #42
	ldp x29, x30, [sp], #16
	retw29
	ret
</pre>
</details>

**Comment by pacak** [comment]
`--simplify` removes most of the things that are not instructions or labels.

I guess this is technically an instruction..
```
	.long	3577430696
```
What about `retw29`? Is it some kind of copy-paste error or the actual output?

**Comment by elagergren-spideroak** [comment]
> I guess this is technically an instruction..

Yeah, sorry.  For reference, this is an _example_ of the Rust code that generates those `.long xxx` instructions:

```rust
        /// Enable DIT.
        ///
        /// # Safety
        ///
        /// DIT must be supported. Check with [`is_supported`].
        #[target_feature(enable = "dit")]
        pub unsafe fn enable() {
            // NB: we write out the opcode because DIT is v8.4+
            // and LLVM rejects the insructions when compiling
            // for older architectures.
            //
            // SAFETY: see section C5.2.4 of the reference
            // manual.
            unsafe {
                asm!(".long 0xd503415f /* msr dit, #1 */");
            }
        }
```

> What about retw29? Is it some kind of copy-paste error or the actual output?

Not sure. Let me re-paste the output:

<details>
<pre>
$ cargo asm
    Finished release [optimized] target(s) in 0.00s

.section __TEXT,__text,regular,pure_instructions
	.build_version macos, 11, 0
	.globl	dit::with_dit
	.p2align	2
dit::with_dit:
Lfunc_begin0:
	.cfi_startproc
	stp x29, x30, [sp, #-16]!
	.cfi_def_cfa_offset 16
	mov x29, sp
	.cfi_def_cfa w29, 16
	.cfi_offset w30, -8
	.cfi_offset w29, -16
	mov x9, #68719411200
	movk x9, #49168
	ldr x8, [x9]
	tbz x8, #57, LBB0_4
	; InlineAsm Start
	.long	3577430696
	; InlineAsm End
	tbnz w8, #24, LBB0_4
	; InlineAsm Start
	.long	3573760351
	; InlineAsm End
	ldr x8, [x9]
	tbz x8, #57, LBB0_5
	; InlineAsm Start
	.long	3573760095
	; InlineAsm End
	b LBB0_5
	ldr xzr, [x9]
LBB0_5:
	mov w0, #42
	.cfi_def_cfa wsp, 16
	ldp x29, x30, [sp], #16
	.cfi_def_cfa_offset 0
	.cfi_restore w30
	.cfi_restore w29
	ret
0:0 /tmp/dit [main +4 !3] $ cargo asm --simplify
    Finished release [optimized] target(s) in 0.00s

dit::with_dit:
Lfunc_begin0:
	stp x29, x30, [sp, #-16]!
	mov x29, sp
	mov x9, #68719411200
	movk x9, #49168
	ldr x8, [x9]
	tbz x8, #57, LBB0_4
	tbnz w8, #24, LBB0_4
	ldr x8, [x9]
	tbz x8, #57, LBB0_5
	b LBB0_5
	ldr xzr, [x9]
LBB0_5:
	mov w0, #42
	ldp x29, x30, [sp], #16
	ret
</pre>
</details>

**Comment by pacak** [comment]
Will change to keep data definitions in place.

**Comment by elagergren-spideroak** [comment]
@pacak thanks. And also thank you for this tool!

**Comment by pacak** [comment]
Gnu assembler manual contains this when talking about `.long`:

> Note - this directive is not intended for encoding instructions, and it will not trigger effects like DWARF line number generation. Instead some targets support special directives for encoding arbitrary binary sequences as instructions such as eg `.insn` or `.inst`. 

From the same documentation, arm supports this:
```     
.inst expressions
    Inserts the expressions into the output as if they were instructions, rather than data. 
```

So I think this `.inst` is what you should be using, not `.long`.

But long should now be supported as well.
