### ISSUE TITLE
Debug info included by default in 0.2.33

### ISSUE THREAD

**Issue by DaniPopes** [pacak/cargo-show-asm#269]
`-Cdebuginfo=2` is added to all cargo calls in https://github.com/pacak/cargo-show-asm/pull/268/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR113-R120

This is very verbose, especially for LLVM output, for example 
![image](https://github.com/pacak/cargo-show-asm/assets/57450786/ccb27211-6436-4e23-b37a-da0dc2753837)

**Comment by pacak** [comment]
Oops. I added this temporarily to debug stuff... Will fix in a new version today/tomorrow.

Need to add better tests - #79
