### ISSUE TITLE
Missing/incorrect line information

### ISSUE THREAD

**Issue by orf** [pacak/cargo-show-asm#277]
Hello,
Thank you for this awesome tool - it's super useful. The following is likely an issue with Rust and/or llvm, but I wanted to open it here in case you had any insights? Basically, it seems that something is completely mangling the DWARF information during an optimization pass. If you can shed any light whatsoever then I'd be really grateful, as I'm interested and would love to learn more.

I was experimenting with a simple example:

```rust
#[no_mangle]
pub fn add(left: usize, right: usize) -> usize {
    let result = left + right;
    if result < 10 {
        return 3;
    }
    return result
}
```

On MacOS and Linux I get the following result when running `cargo asm -p test-lib --rust --simplify`:

```
add:
		// /code/test-lib/src/lib.rs : 3
		let result = left + right;
	add x9, x1, x0
	mov w8, #3
	cmp x9, #10
	csel x0, x8, x9, lo
		// /code/test-lib/src/lib.rs : 8
		}
	ret
```

The if condition is missing from the output entirely, whilst being present in the assembly. Looking at the output from `dwarfdump` shows that it's definitely not there - only lines 3 and 8 are referenced.

Interestingly, compiling it with `x86_64-apple-darwin` rather than `aarch64-apple-darwin` (or any `aarch64-*` target) outputs more realistic looking line information, including the function name and the conditionals:

```
cargo asm -p test-lib --rust --simplify --target=x86_64-unknown-linux-gnu
   Compiling test-lib v0.1.0 (/code/test-lib)
    Finished `release` profile [optimized] target(s) in 0.03s

add:
		// /code/test-lib/src/lib.rs : 3
		let result = left + right;
	lea rcx, [rdi + rsi]
		// /code/test-lib/src/lib.rs : 4
		if result < 10 {
	cmp rcx, 10
	mov eax, 3
	cmovae rax, rcx
		// /code/test-lib/src/lib.rs : 8
		}
	ret
```

Looking at the optimized LLVM IR:

```
cargo asm -p test-lib --rust --simplify --release --llvm
   Compiling test-lib v0.1.0 (/code/test-lib)
    Finished `release` profile [optimized + debuginfo] target(s) in 0.03s

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable
define noundef i64 @add(i64 noundef %left, i64 noundef %right) unnamed_addr #0 !dbg !6 {
start:
  tail call void @llvm.dbg.value(metadata i64 %left, metadata !13, metadata !DIExpression()), !dbg !18
  tail call void @llvm.dbg.value(metadata i64 %right, metadata !14, metadata !DIExpression()), !dbg !18
  %result = add i64 %right, %left, !dbg !19
  tail call void @llvm.dbg.value(metadata i64 %result, metadata !15, metadata !DIExpression()), !dbg !20
  %_4 = icmp ult i64 %result, 10, !dbg !21
  %.result = select i1 %_4, i64 3, i64 %result, !dbg !20
  ret i64 %.result, !dbg !22
}
```

The  3rd `@llvm.dbg.value` seems to be the `if` condition we want to display, but it's somehow dropped.

**Comment by pacak** [comment]
> Thank you for this awesome tool - it's super useful.

:heart: 

> If you can shed any light whatsoever then I'd be really grateful, as I'm interested and would love to learn more.

I have absolutely no idea right now :) Complaining upstream with the right example is probably the fastest way to get this fixed. I can try to look into that as well...

FWIW `--release` is the default option.

**Comment by pacak** [comment]
So if you are going to complain upstream - please let me know, otherwise I'll see what I can do closer to the weekend.

**Comment by orf** [comment]
Why is it that the moment you post something, some insight comes to you? The if condition is being optimized out, but in a non-obvious way.

I threw the code into compiler explorer and went to down a bit:
- Rust code with optimization pipeline: https://godbolt.org/z/Y9K5YKfKd
- LLVM IR + Clang with optimization pipeline: https://godbolt.org/z/6vEqze6f3

We can track the `!21 = !DILocation(line: 4, column: 8, scope: !16)` bit through the pipeline. It all goes to shit in the `AArch64 Instruction Selection` pass. The conditional seems to be lowered to this, and the location becomes untracked:

```
%3:gpr64 = SUBSXri %2:gpr64common, 10, 0, implicit-def $nzcv, debug-location !21; example.rs:0
%4:gpr32 = MOVi32imm 3
%5:gpr64 = SUBREG_TO_REG 0, killed %4:gpr32, %subreg.sub_32
%6:gpr64 = CSELXr killed %5:gpr64, %2:gpr64common, 3, implicit $nzcv, debug-location !21; example.rs:0
```

I have no clue what I'm doing so I threw it into chat-gpt and asked it to explain what the fuck this all means because it's 11:30pm and I'm looking at compiler output:

> `%3:gpr64 = SUBSXri %2:gpr64common, 10, 0`
> Subtracts 10 from %2:gpr64common, setting condition flags in $nzcv.
> `%4:gpr32 = MOVi32imm 3`
> Moves the immediate value 3 into %4:gpr32.
> `%5:gpr64 = SUBREG_TO_REG 0, killed %4:gpr32, %subreg.sub_32`
> Converts the 32-bit value %4:gpr32 to a 64-bit value %5:gpr64.
> `%6:gpr64 = CSELXr killed %5:gpr64, %2:gpr64common, 3`
> Conditionally selects between %5:gpr64 and %2:gpr64common based on the condition flags in $nzcv.

It could be hallicinating and I'd never know, but it seems on point. Googling `arm nzcv flag` tells me that it is:

> Zero condition flag. Set to 1 if the result of the last flag-setting instruction was zero, and to 0 otherwise. A result of zero often indicates an equal result ...

So the if conditional is being lowered to a subtraction and a flag comparison to see if the result was 0... ok. sure. I guess with this it sort of makes sense to drop the location info, because it's clearly a very different instruction? idk.

However at some point this nonsense is optimized "_back_" into a simple comparison instruction, but at this point the location info is lost.

![image](https://github.com/pacak/cargo-show-asm/assets/1027207/c69cb775-361a-4f40-aa3a-4bf2fff0a22a)

**Comment by orf** [comment]
thanks for your offers of help @pacak, I really appreciate the offer, but I don't want to take up any of your time! I think I'll open an issue on the llvm bugtracker, because even if the conditional is being optimized away the location info should still be tracked, IMO. Unless it turns out the issue is somehow with the IR that's being generated by `rustc`. but it doesn't _seem_ obviously wrong 🤷 

i'll have a play either way tomorrow 🎵

**Comment by pacak** [comment]
> and sorry for the github-issue rubber ducking

It was a fun read either way and if you are going to complain upstream - please drop a link to the ticket :)

**Comment by orf** [comment]
I've added an issue [here](https://github.com/llvm/llvm-project/issues/92875), I hope this is the right place. Let's see!

I might try and dig a bit deeper into it once I'm back from my holidays.
