### ISSUE TITLE
Missed no_mangle symbol in no_std/no_main Windows code

### ISSUE THREAD

**Issue by evmar** [pacak/cargo-show-asm#281]
For a little test program I've been looking at cargo-show-asm immediately dumps the assembly for one function within the program. 
This is confusing, because I expected it to prompt me about which function to dump.
 
Debugging it a bit I believe the cause is it only found one function and printed it directly.  It only found one function because everything but one was inlined into the main function, and it missed the main function.

The test program is a no-main no-std Windows program, which looks like this:

```
#![no_main]
#![no_std]
#![windows_subsystem = "console"]

...

#[no_mangle]
pub unsafe extern "C" fn mainCRTStartup() {
```

I traced a bit and I think the relevant assembly parts are:

```
	.section	.text,"xr",one_only,__ZN6no_std3fmt3Fmt6bin_u817hdd9f71822aa230edE
	.p2align	4, 0x90
__ZN6no_std3fmt3Fmt6bin_u817hdd9f71822aa230edE:
Lfunc_begin0:
```

which cargo-show-asm properly demangles and identifies as the single function (no_std::fmt::Fmt::bin_u8), and then later

```
	.section	.text,"xr",one_only,_mainCRTStartup
	.globl	_mainCRTStartup
	.p2align	4, 0x90
_mainCRTStartup:
Lfunc_begin1:
```

which gets to [here](https://github.com/pacak/cargo-show-asm/blob/74b9146be0f47be04569b412a236c6e39c56e485/src/asm.rs#L139)

and then fails to match because cargo-show-asm is looking for the prefix `.text.` which doesn't match the above `.text,` text.

I am not sure what the proper fix is, but I'd be happy to debug, provide more info, and write a patch if you could guide me.

**Comment by pacak** [comment]
It is looking for `.text.` because on Linux typical section looks like this:

```asm
.section ".text.core::ptr::drop_in_place<ahash::random_state::DefaultRandomSource>","ax",@progbits
        .p2align        4, 0x90
        .type   core::ptr::drop_in_place<ahash::random_state::DefaultRandomSource>,@function
_ZN4core3ptr61drop_in_place$LT$ahash..random_state..DefaultRandomSource$GT$17h79a63d5e9281aa35E:
        .cfi_startproc
        ret
        .size   core::ptr::drop_in_place<ahash::random_state::DefaultRandomSource>, .Lfunc_end2-core::ptr::drop_in_place<ahash::random_state::DefaultRandomSource>
        .cfi_endproc
```

In general it's described here https://sourceware.org/binutils/docs/as/Section.html and looks like this:

```
.section name [, "flags"[, @type[,flag_specific_arguments]]]
```

Looks like on Windows it's different.

It would be very helpful if you could find the documentation to how it is supposed to look like and add a special case to handle it for Windows like `.text.` does it for Linux and `__TEXT` a few lines above - for MacOS.

Meanwhile I'll spend some time trying to remember how it is supposed to work - shame on me for lack of comments.

**Comment by evmar** [comment]
It looks like maybe this is the relevant bit of LLVM docs:
https://llvm.org/docs/Extensions.html#section-directive

which means my
```
.section	.text,"xr",one_only,_mainCRTStartup
```

is indirectly saying `.globl _mainCRTStartup`.

It seems like maybe we should do some parsing similar to as done [here](https://github.com/pacak/cargo-show-asm/blob/74b9146be0f47be04569b412a236c6e39c56e485/src/asm.rs#L129) perhaps?

I might start by adding some tests that demonstrate the formats seen on Linux/Mac/Windows, do you have a pointer to where that should be?

**Comment by evmar** [comment]
I think we could avoid attempting to parse these .section bits by just `get_item_in_section(".text,"xr",one_only,", ...)` perhaps.

**Comment by evmar** [comment]
...oh wait, there's also an explicit `.globl` line too, no special parsing needed, we just need to follow the same logic as Mac.

**Comment by evmar** [comment]
Retitled bug to reflect how I think this is just a consequence of `no_mangle` on the main function.

**Comment by evmar** [comment]
```
     match lines.get(sec_start) {
         Some(Statement::Directive(Directive::SectionStart(ss))) => {
-            if *ss == "__TEXT,__text,regular,pure_instructions" {
+            if *ss == "__TEXT,__text,regular,pure_instructions"
+                || ss.starts_with(".text,\"xr\",one_only,")
+            {
                 // macOS first symbol, symbols after this are resolved using
```

is enough to produce

```
Try one of those by name or a sequence number
0 "mainCRTStartup" [13]
1 "ops::fmt_flags" [163]
2 "ops::test" [155]
3 "rust_begin_unwind" [15]
```

where symbols 0 and 3 weren't found before.

**Comment by pacak** [comment]
> ...oh wait, there's also an explicit .globl line too, no special parsing needed, we just need to follow the same logic as Mac.

Yea, this works too, but we still need to detect that it might be there before applying that logic. Same as Mac does.

> I might start by adding some tests that demonstrate the formats seen on Linux/Mac/Windows, do you have a pointer to where that should be?

I'm afraid there's no unit tests for no_mangle style sections. There are some parsing tests under `asm/statements.rs` and I'm running win/linux/mac in CI, but it's not perfect (#79) - if it detects it - it works, if it fails to detect it - I start looking at what's wrong :)

**Comment by evmar** [comment]
Coincidentally, I happen to be an expert in making Linux Rust builders produce win32 binaries!  Here's a worked example of a no_std Windows program:

https://github.com/evmar/retrowin32/commit/25b54d8032968c20c10636daa39ab7391ac29ee6

however you need to download .lib files from Microsoft for it to work, probably don't wanna do it on CI.

**Comment by pacak** [comment]
Are you planning to make your own pull request? If not - I'll take your changes from https://github.com/pacak/cargo-show-asm/issues/281#issuecomment-2143615096 and make a release with that.

**Comment by evmar** [comment]
I see, a test for multi-line matching is a little harder.

https://github.com/pacak/cargo-show-asm/pull/282
