### ISSUE TITLE
Subcommand doesn't appear to understand --config

### ISSUE THREAD

**Issue by zesterer** [pacak/cargo-show-asm#305]
Cargo allows you to specify additional [configuration](https://doc.rust-lang.org/cargo/reference/config.html) via the `--config <path>` argument, but `cargo asm` doesn't appear to understand this.

**Comment by pacak** [comment]
It's not `--config <path>`, but `--config KEY=VAL`, but sure, I can add it.

**Comment by zesterer** [comment]
Thanks so much for the rapid turnaround on this, much appreciated!

**Comment by zesterer** [comment]
> It's not `--config <path>`, but `--config KEY=VAL`, but sure, I can add it.

Ah, I realise I should have read this message. Actually, it *is* `--config <path>` (or at least, it can be). It allows you to pass an additional `.cargo/config.toml`-style configuration file to cargo.

**Comment by pacak** [comment]
New version accepts whatever you pass to `--config` without trying to pass it further and passes it to `cargo`. If you pass path to a file - it will be passed to cargo as well. Are you sure it doesn't work?

**Comment by zesterer** [comment]
My bad: it works, but I've got to pass it after the `asm` subcommand, whereas vanilla cargo commands accept it before the subcommand.

**Comment by pacak** [comment]
Interesting. `cargo` eats up `--config foo` and only passes me what goes after `asm`. Not much I can do about it. Is it actually working as expected with things like `cargo run`?

**Comment by zesterer** [comment]
Bizarre. I don't know exactly how subcommands work (never written one), but I would have assumed that cargo would do the necessary housekeeping without your intervention. Ah well.

> Is it actually working as expected with things like cargo run?

Yes.

**Comment by pacak** [comment]
> I don't know exactly how subcommands work (never written one)

Make a binary `cargo-foo`, place it in your path. type `cargo foo more args`, cargo will call your app with `foo more args` arguments. That is it will pass command name along with all the arguments after it to your app.
