### ISSUE TITLE
Prevent linking of instances of the same function

### ISSUE THREAD

**Issue by e00E** [pacak/cargo-show-asm#338]
I have two functions that happen to have the same assembly. In the output of cargo-asm this looks like this:

```asm
.set my_crate::foo, my_crate::bar
```

The assembly for `bar` contains the actual assembly.

This is annoying because I would like to see the assembly immediately in `foo`. I do not want to see this output and then have to switch to `bar`. Both functions are marked inline-never.

I noticed that whether I get the `.set` behavior depends on what the [lto setting](https://doc.rust-lang.org/cargo/reference/profiles.html#lto) is. I'm not sure whether that is relevant.

**Comment by pacak** [comment]
This linking is done by rustc/llvm so I can't really prevent it. Forbidding lto and setting unreasonably high codegen unit count would help if not for https://github.com/rust-lang/cargo/issues/13672

What I can try is to detect this kind of behavior and make it so `your_crate::bar` is displayed alongside the output you get right now either unconditionally or using recursive context flag...
