### ISSUE TITLE
Support `--profile` argument

### ISSUE THREAD

**Issue by Robbepop** [pacak/cargo-show-asm#63]
I have a project for which I would like to see the assembly output of a certain [Cargo profile](https://doc.rust-lang.org/cargo/reference/profiles.html), given `--profile bench` instead of using the usual `--release` compilation.
Unfortunately this is not (yet) supported by the `cargo-asm` tool.
Would it be possible to implement this?

**Comment by pacak** [comment]
If you install it from `custom` branch - it should support `--profile`. I'll release it once I fix some other open tickets. Can you check if it solves your problem? You can do something like `cargo install --git https://github.com/pacak/cargo-show-asm --branch custom` to get it.

**Comment by Robbepop** [comment]
It is fine i will just wait for the next release then and use the hack i got so far. thanks!

**Comment by pacak** [comment]
Published 0.1.24
