### ISSUE TITLE
Question: What are the requirements for a function to be displayed?

### ISSUE THREAD

**Issue by Robbepop** [pacak/cargo-show-asm#64]
Today I wanted to try out this tool to examine the generated assembly of a particular function in my project.
However, the function that I was most interested in unfortunately did not even show up in the filters.
I tried to make it public and exported it etc but all that did not work. Also I could not find documentation about how to make a function in a crate displayable via this tool.
It would be neat to have this information available. :) And in case I missed information that is already available somewhere please point me to it.

**update:** I got `cargo-asm` to show the function. The problem was that the function was generic and thus had no proper monomorphized instantiation. I fixed it by defining a new function with default generic parameters in place.

**Comment by pacak** [comment]
Right, `rustc` won't be able to generate anything if it doesn't know the exact type

**Comment by Robbepop** [comment]
Thank you for the answer. This can be closed then. Nice tool btw! It really helped me today to figure out some performance regression. :)

**Comment by pacak** [comment]
I'll close once I update the docs or something like that

**Comment by Robbepop** [comment]
Keep up the good work on the tool!
