### ISSUE TITLE
Error: Cannot locate the path to the asm file

### ISSUE THREAD

**Issue by sporksmith** [pacak/cargo-show-asm#82]
In [shadow](https://github.com/shadow/shadow) (an admittedly complex hybrid C/Rust project that uses build scripts, bindgen, and cbindgen...) I'm getting the following error:

```
# Use shadow's helper to initialize a cmake build dir
$ ./setup build debug
...
# Try using cargo asm:
$ (cd src && cargo asm -p shadow-rs --lib "shadow_rs::main::host::Host::default_ip")
...
Error: Cannot locate the path to the asm file
```

I tried on both Rust 1.63.0 and 1.65.0

**Comment by pacak** [comment]
Can you run it with `-vvv` to see if it is looking anywhere near where it should be looking?

**Comment by sporksmith** [comment]
Sure:

```
$ cargo asm --manifest-path=src/Cargo.toml -p shadow-rs --lib --target-dir build/src/target -vvv "shadow_rs::main::host::Host::default_ip"
Artifact files: ["  /home/jnewsome/projects/shadow/dev/build/src/target/release/deps/libbytes-b6d5f55491c0e232.rlib " , Finished"/home/jnewsome/projects/shadow/dev/build/src/target/release/deps/libbytes-b6d5f55491c0e232.rmeta "release [optimized] target(s) in 0.07s]

Error: Cannot locate the path to the asm file
```

Both of the referenced files exist, though I wonder if the leading and trailing whitespace inside the quoted strings is an issue.

```
$ ls /home/jnewsome/projects/shadow/dev/build/src/target/release/deps/libbytes-b6d5f55491c0e232.rlib
/home/jnewsome/projects/shadow/dev/build/src/target/release/deps/libbytes-b6d5f55491c0e232.rlib
$ ls /home/jnewsome/projects/shadow/dev/build/src/target/release/deps/libbytes-b6d5f55491c0e232.rmeta
/home/jnewsome/projects/shadow/dev/build/src/target/release/deps/libbytes-b6d5f55491c0e232.rmeta
```

**Comment by sporksmith** [comment]
Or maybe I'm just seeing two log lines get interwoven. "Artifact files..." and "Finished..."

**Comment by sporksmith** [comment]
> https://github.com/pacak/cargo-show-asm/issues/82 - looks like there's something strange going on with rlib, I'm trying to go though artifacts as they are parsed and I don't see anything related to shadow-rs even though .s files are created. I wonder if you have any ideas, if not - I'll hack something to dig through the files directly in case of rlib...

Was this comment meant to be on this issue?

One thing that's a little odd about this crate is that it supports both rlib and staticlib output: https://github.com/shadow/shadow/blob/6fc290de3f88f79f5072661df0d728d65c9307d9/src/main/Cargo.toml#L10

I think normally *both* are created when compiling with `--lib`, but maybe this is confusing things somehow?

**Comment by pacak** [comment]
> Was this comment meant to be on this issue?

Yes. Code that is having a problem was introduced in that MR and I was trying to reach the author.

> I think normally both are created when compiling with `--lib`, but maybe this is confusing things somehow?

Probably. Either way it's a good test case and I'll make sure it works. Planning to look closer into the problem tomorrow.

**Comment by sporksmith** [comment]
> Probably. Either way it's a good test case and I'll make sure it works.

I tried removing `staticlib` from the `crate-type` list, but got the same result

>  Planning to look closer into the problem tomorrow.

Thanks! This isn't in any way urgent for me, but it'd be nice if we could use this tool :)

**Comment by pacak** [comment]
Can you check if `rlib` branch solves the problem for you?

**Comment by pacak** [comment]
Okay, I'll fix the tests and release a new version. Thank you for reporting a problem.

**Comment by pacak** [comment]
Released 0.2.3

**Comment by sporksmith** [comment]
Confirmed works for me at the latest release. Thank you for the quick turnaround!

**Comment by benjamin051000** [comment]
Hi, I'm having this issue trying to run the tool with https://github.com/louis-e/arnis. 
```
❯ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/benjamin/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.84.0 (9fc6b4312 2025-01-07)

❯ cargo asm --version
Version: 0.2.47

❯ cargo asm --bin arnis --no-default-features

<lots of output since it is compiling...>

Error: Cannot locate the path to the asm file
```

**Comment by pacak** [comment]
> What's going on?

LTO strikes again. Made a new ticket. Currently there are two workarounds - removing lto from `Cargo.toml` fixes the problem, but also you can install `cargo-show-asm` with `disasm` feature and run `cargo asm --bin arnis --no-default-features --disasm`. This works to some extent and will show you the actual output.

**Comment by benjamin051000** [comment]
Thank you!!
